### ISSUE TITLE
check_schema: is_nullable should be optional parameter

### ISSUE THREAD

**Issue by RunsFor** [tarantool/ddl#12]
From tarantool [space:format()](https://www.tarantool.io/en/doc/2.2/book/box/box_space/#lua-function.space_object.format) documentation:

> the optional is_nullable value may be either true or false

```
tarantool> (function()
         >     local res, err = require('ddl').check_schema({
         >         spaces = {
         >             processes = {
         >                 engine = 'memtx',
         >                 is_local = false,
         >                 temporary = false,
         >                 format = {
         >                     { name = 'foo', type = 'string' }
         >                 },
         >                 indexes = {},
         >             }
         >         }})
         >     return res, err
         > end)()
---
- null
- 'space["processes"].fields["foo"]: bad argument ''is_nullable'' (boolean expected,
  got nil)'
...
```

Please make it consistent with tarantool space format

**Comment by rosik** [comment]
I don't agree that it should. DDL schema format isn't a copy of box options, and we decided it should be more explicit than in box. So there are no optional fields in schema.

**Comment by RunsFor** [comment]
Ok then add more info about it in README. Right now it is confusing, since you borrowed most of the semantics from tarantool box api.
