### ISSUE TITLE
Make API for getting date from success applied version of DDL

### ISSUE THREAD

**Issue by rosik** [tarantool/ddl#29]
Originally posted as a card on cartridge dashboard by @artur-barsegyan.

Clarify it, please, if it's still relevant.

**Comment by artur-barsegyan** [comment]
Sure. We can apply a current DDL to a cluster but we don't have any information in the UI about:

- is the current modifications are already applied?
- what was the time of the last apply?

**Comment by rosik** [comment]
It's not a responsibility of the ddl module. Please, move it to the cartridge.
