### ISSUE TITLE
[2pt] Create a cartridge role for ddl.get_schema

### ISSUE THREAD

**Issue by akudiyar** [tarantool/ddl#50]
Related to https://github.com/tarantool/cartridge-java/issues/54

Consider a connector that needs to get the spaces schema from a Tarantool instance or a Cartridge cluster. In a Cartridge, we'll have to define a role containing the public API function for getting the schema. 

I suggest exposing the `get_schema` method in a public role like it is done with CRUD API (see https://github.com/tarantool/crud/pull/58).

**Comment by rosik** [comment]
It's already there. See https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge/#global-functions

```lua
_G.cartridge_get_schema()
_G.cartridge_set_schema(schema)
```

**Comment by akudiyar** [comment]
Don't hurry up, we need to discuss this.

1) `cartridge.get_schema` returns schema in YAML format, which requires a connector to use a YAML library, which sometimes is not desired (I hope to not add the YAML library into cartridge-java at the moment since it is not needed for anything else yet). 
2) When using tarantool/migrations the `ddl.get_schema` API can be called from a router node, in this case that call will be more lightweight  than `cartridge.get_schema`
3) The output of `cartridge.get_schema` is not equal to `ddl.get_schema`. At least, the latter shows the internal `_bucket` space which may be useful in a connector.
