### ISSUE TITLE
Add sharding function section to ddl schema

### ISSUE THREAD

**Issue by AnaNek** [tarantool/ddl#71]
RFC - https://github.com/tarantool/crud/issues/27#issuecomment-885849411

**Comment by AnaNek** [comment]
## Sharding function API in ddl schema

### With `body` field

**Description:** `sharding_func` section can contain string value or table value. String value is for vshard sharding function identifier like `strcrc32`/`mpcrc32`, for sharding function specified as `dot.notation.func` and for sharding function name from `_G`. Custom sharding function can be passed as Lua code as table with `body` field: 

```lua
sharding_func = 'mpcrc32' | 'strcrc32' | 'dot.notation.func' | {body = 'function(key) return <...> end'},
    <...>
```

**Pros:**

1. Similar API exists: `box.func = {body = “...”}`;
2. Allows to differentiate whether it is an executable function or an identifier.

**Cons:**

1. API looks more complicated.

### Without `body` field

**Description:** `sharding_func` section can contain only a string value. 

```lua
sharding_func = 'mpcrc32' | 'strcrc32' | 'dot.notation.func' | 'function(key) return <...> end',  <...>
```

**Pros:**

1. API looks simpler.

**Cons:**

1. The definition of the function name / function body is implicit, in general, such API looks like a potential security problem (but it is important for us only because of the desire to make api similar to existing ones in the future).

**Comment by unera** [comment]
I think the second variant is ok.

**Comment by Totktonada** [comment]
@AnaNek Thank you for the proposals!

There were several chatting rounds around those proposals and the short summary is the following.

1. We'll not implement shortcuts 'mpcrc32' and 'strcrc32' for now.
2. We'll use the `{body = 'function(key) return <...> end'}` syntax (the first variant).
