### ISSUE TITLE
Caching of the sharding keys

### ISSUE THREAD

**Issue by 0x501D** [tarantool/ddl#88]
We have cache for sharding function: #85.  
Logically, we can also cache the sharding keys and get rid of get_metadata() finction.

**Comment by Totktonada** [comment]
Caching of the sharding function aims to speed up the `ddl.bucket_id()` function, which looks pretty hot (i.e. called in each request). What is the goal here?

**Comment by 0x501D** [comment]
I agree, caching the sharding keys is meaningless.
